### ISSUE TITLE
Reproducing the results

### ISSUE THREAD

**Issue by Gjergj121** [dolev104/neural_congealing#3]
Hi. 

I have been trying to reproduce the PCK-transfer values that you state in your paper, by using a dataset of 25 images of dogs, but I keep getting very low values. I have been using your config.yaml file, and I also have not changed anything else from the model. What can I be doing wrong?

Thank you in advance.

**Comment by dolev104** [comment]
Hi @Gjergj121,

For the evaluation sets, we allow horizontal flips (which is not set in the `config.yaml` file. We set `ext_horizontal_flips` to `True`, which you'll notice is the only difference with `config_w_flips.yaml`). 
Also, due to the extreme deformations that are present in the evaluation sets mentioned in the paper, we increase robustness by relaxing rigidity coefficients and learning the atlas gradually (see Appendix A.4.1 in the paper for more details).

I've just added the config file `config_eval_sets.yaml` that is suited for reproducing the result you want, so it'll be easier to use.

In general, for convenience, the pretrained models are saved together with the configuration, so you can also see it there -- you can download pretrained models from the paths provided in `README.md` (provided for [sample sets](https://github.com/dolev104/neural_congealing#download-sample-image-sets), [Spair-71K](https://github.com/dolev104/neural_congealing#spair-71k) and [CUB](https://github.com/dolev104/neural_congealing#cub-200-2011)).

**Comment by dolev104** [comment]
Hi @Gjergj121,

For the evaluation sets, we allow horizontal flips (which is not set in the `configs/config.yaml` file. We set `ext_horizontal_flips` to `True`, which you'll notice is the only difference with `configs/config_w_flips.yaml`).
Also, due to the extreme deformations that are present in the evaluation sets mentioned in the paper, we increase robustness by relaxing rigidity coefficients and learning the atlas gradually (see Appendix A.4.1 in the paper for more details).

I've just added the config file `configs/config_eval_sets.yaml`, so it'll be easier to use.

In general, for convenience, the pretrained models are saved together with the configuration, so you can also see it there -- you can download pretrained models from the paths provided in `README.md` (provided for [sample sets](https://github.com/dolev104/neural_congealing#download-sample-image-sets), [Spair-71K](https://github.com/dolev104/neural_congealing#spair-71k) and [CUB](https://github.com/dolev104/neural_congealing#cub-200-2011)).

**Comment by Gjergj121** [comment]
Thanks, when I trained using configs/config_eval_sets.yaml, I could reproduce the results.
